### ISSUE TITLE
No plugging found

### ISSUE THREAD

**Issue by mrdado** [kaszito/homebridge-eedomus#5]
I'm having the following issue on attempt to run Homebridge> Can someone help me please ?

[11/24/2016, 10:52:29 PM] ====================
[11/24/2016, 10:52:29 PM] ERROR LOADING PLUGIN homebridge-eedomus:
[11/24/2016, 10:52:29 PM] Error: ENOENT: no such file or directory, open '/home/pi/.homebridge/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-eedomus/index.js:8:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
[11/24/2016, 10:52:29 PM] ====================
[11/24/2016, 10:52:33 PM] Loaded plugin: homebridge-platform-orvibo
[11/24/2016, 10:52:33 PM] Registering platform 'homebridge-platform-orvibo.Orvibo'
[11/24/2016, 10:52:33 PM] ---
[11/24/2016, 10:52:33 PM] Loaded config.json with 4 accessories and 0 platforms.
[11/24/2016, 10:52:33 PM] ---
[11/24/2016, 10:52:33 PM] Loading 4 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'eedomus' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:251:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:78:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by mrdado** [comment]
Detail: I'm installing on a mac.

**Comment by starcrouz** [comment]
Hi, 
Did you create the config file ? 
The error is : 
no such file or directory, open '/home/pi/.homebridge/config.json'

**Comment by kaszito** [comment]
First check your config.file. Then try pasting your config.json file in http://jsonlint.com to validate it.

**Comment by mrdado** [comment]
@starcrouz : normally yes. I've followed the steps written in the tutorial. I'll start all over again to see what happens.

@kaszito : I'll try that.

Thank you
